//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `mixer` program ID.
  pub const MIXER_ID: Pubkey = pubkey!("Aijc1oXBzSRJKWRYrtj6e8osBASNDkkgREziGGWYvK9p");

