/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import { getMixerErrorFromCode, getMixerErrorFromName } from '../errors';

export const MIXER_PROGRAM_ID =
  'Aijc1oXBzSRJKWRYrtj6e8osBASNDkkgREziGGWYvK9p' as PublicKey<'Aijc1oXBzSRJKWRYrtj6e8osBASNDkkgREziGGWYvK9p'>;

export function createMixerProgram(): Program {
  return {
    name: 'mixer',
    publicKey: MIXER_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getMixerErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getMixerErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getMixerProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('mixer', clusterFilter);
}

export function getMixerProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'mixer',
    MIXER_PROGRAM_ID,
    clusterFilter
  );
}
