//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#deposit_sol;
  pub(crate) mod r#deposit_spl;
  pub(crate) mod r#withdraw_sol;
  pub(crate) mod r#withdraw_spl;

  pub use self::r#deposit_sol::*;
  pub use self::r#deposit_spl::*;
  pub use self::r#withdraw_sol::*;
  pub use self::r#withdraw_spl::*;

